services:
  tedx-updater:
    image: ${DOCKER_IMAGE}
    container_name: tedx_updater
    env_file:
      - .env
    volumes:
      - ./videos:/s1146363/videos:ro
      - ./downloads:/s1146363/downloads
    working_dir: /s1146363
    restart: "no"
